version: "3.4"

services: 
  ovpn:
    build: ./
    image: luca/openvpn:latest
    volumes:
      - /mnt/data/containers/clientsOVPN:/home/OVPN/clients/ovpn
    network_mode: host
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    